/// Utilities for World Server authentication
import 'dart:typed_data';
import '../crypto/utils.dart';

/// Calculate the digest for CMSG_AUTH_SESSION
/// 
/// The digest is calculated as:
/// SHA1(account_name + t[4] + local_challenge + auth_seed + session_key)
/// 
/// Where:
/// - account_name: account name in UPPERCASE (must match the case used in SRP6)
/// - t[4]: always {0x00, 0x00, 0x00, 0x00}
/// - local_challenge: random 4 bytes generated by client
/// - auth_seed: 4 bytes received in SMSG_AUTH_CHALLENGE
/// - session_key: 40 bytes received from auth server (K from SRP6)
Uint8List calculateAuthDigest({
  required String accountName,
  required Uint8List localChallenge,
  required Uint8List authSeed,
  required Uint8List sessionKey,
}) {
  assert(localChallenge.length == 4, 'localChallenge must be 4 bytes');
  assert(authSeed.length == 4, 'authSeed must be 4 bytes');
  assert(sessionKey.length == 40, 'sessionKey must be 40 bytes (K from SRP6)');

  final bb = BytesBuilder();

  // Account name (must already be uppercase)
  bb.add(accountName.codeUnits);

  // t[4] = {0x00, 0x00, 0x00, 0x00}
  bb.add([0x00, 0x00, 0x00, 0x00]);

  // Local challenge (4 bytes)
  bb.add(localChallenge);

  // Auth seed (4 bytes from SMSG_AUTH_CHALLENGE)
  bb.add(authSeed);

  // Session key (40 bytes from auth server)
  bb.add(sessionKey);

  // Calculate SHA1
  return sha1Bytes(bb.toBytes());
}
